-- BLOCK 1: SELECT

-- Q1. Display all columns from the employee table.

SELECT *
FROM employee;

-- Q2. Display only employee name and salary.

SELECT emp_name, salary
FROM employee;

-- Q3. WAQTD all the details from the EMP table 
SELECT * 
FROM EMP;

-- Q4. WAQTD NAMES OF ALL THE EMPS
SELECT ENAME 
FROM EMP;

-- Q5. WAQTD NAME AND SALARY GIVEN TO ALL THE EMPS 
SELECT ENAME , SAL 
FROM EMP;

-- Q6. WAQTD EMPID AND DEPTNO OF ALL THE EMPS IN EMP TABLE 
SELECT EMPID , DEPTNO 
FROM EMP;

-- Q7. WAQTD ENAME AND HIREDATE OF ALL THE EMPS 
SELECT ENAME , HIREDATE 
FROM EMP;

-- Q8. WAQTD NAME AND DESIGNATION OF ALL THE EMPS 
SELECT ENAME , JOB 
FROM EMP;

-- Q9. WAQTD NAME , JOB ,SAL GIVE ALL THE EMP;
SELECT ENAME , JOB , SAL 
FROM EMP;

-- Q10. WAQTD DNAME PRESENT IN DEPT TABLE 
SELECT DNAME 
FROM DEPT;

-- Q11. WAQTD DNAME AND LOC PRESENT PRESENT IN DEPT TABLE 
SELECT DNAME , LOC 
FROM DEPT;


-- Explanation:
-- * means all columns.
-- * SELECT is used to display/retrieve data.

-- Remember:
-- * "Show everything" → SELECT *







