-- Q1. WAQTD DETAILS OF THE EMP WHO IS WORKING AS A SALES MAN AND MANAGER 
SELECT * FROM EMP 
WHERE JOB ='SALES MAN'
OR 'MANAGER';

-- Q2. WAQTD DETAILS OF THE EMP WORKING AS A SALES AND EARNING SAL > 1500
SELECT * FROM EMP 
WHERE JOB = 'SALESMAN' 
AND SAL > 1500;
